### ISSUE TITLE
suspend tab rather than unloading

### ISSUE THREAD

**Issue by rofl0r** [JustOff/lull-the-tabs#13]
hi, i'm more concerned about CPU usage by inactive tabs doing javascript stuff (maybe bitcoin mining or rowhammer?) in the background than memory usage. actually i was looking into getting this firefox plugin https://github.com/piroor/suspendtab to work and was looking for example code to make its config dialog work when i encountered your extension.

what do you think about adding an option to pause/suspend execution of a tab instead of unloading it to lull-the-tabs?

i'd actually like every tab to be immediately paused as soon as it gets inactive, so maybe the configuration item to enter the interval could allow floats rather than just ints so one could enter e.g. 0.1...

**Comment by JustOff** [comment]
> what do you think about adding an option to pause/suspend execution of a tab instead of unloading it

This is an interesting idea for a new extension, but I'll leave it to someone else :wink:
