### ISSUE TITLE
WaterFox:  unusable duplicate tabs created when unloaded

### ISSUE THREAD

**Issue by tkwilliams** [JustOff/lull-the-tabs#14]
Unsure whether WaterFox is supported or not, but the addon installs and runs without complaint. It also works almost perfectly, barring this issue I'm reporting.

If an inactive tab is not loaded (e.g. after a restart, or for whatever other reason it's inactive and unloaded), it can be activated and it loads normally.  If it is then unloaded, a second copy of the tab is created on the tab-bar.  Note that this second copy is (correctly) unloaded, but can be loaded as normal by activating it; while the original tab-bar entry remains, but becomes both unselectable and unclosable.  The close button on this original tab responds to mouseover highlighting, but the tab will not in fact close.  I've tried clicking the close button, right-clicking and selecting close, and so on.  The tab is also unresponsive in that it cannot be activated or loaded in any way.  It just sits there on the tab-bar.  This cycle can be repeated as many times as desired, creating a new unusable tab-bar entry each time.

If the entire window is closed, and then re-opened (e.g. via History->Recently Closed Windows) then all tabs (including all previously unusable copies) will be created, with all of them able to activate and load normally.  Restarting the entire application has the same effect.

**Comment by JustOff** [comment]
Well, Waterfox is not actually supported, but you can try [lull-the-tabs-1.5.1b1.xpi.zip](https://github.com/JustOff/lull-the-tabs/files/5721494/lull-the-tabs-1.5.1b1.xpi.zip), which fixes this bug, but otherwise the extension has not been tested or guaranteed to work.

**Comment by tkwilliams** [comment]
Worked like a charm!  Thanks so much.

I actually prefer Palemoon, and use it wherever I can; but sadly on Linux there is a longstanding bug WRT random segfaults, so I've been driven to use WaterFox Classic there.

So far, all of my preferred add-ons have either been compatible out of the box, or worked fine once I updated the manifest to allow installation.

Thanks again!

**Comment by Thyristor-Chopper** [comment]
same bug happens in Pale Moon, using 1.5.2

**Comment by Thyristor-Chopper** [comment]
this bug doesnt happen in BarTab Tycho

**Comment by Thyristor-Chopper** [comment]
this bug however doesnt happen in 1.4.3 (happens in 1.5.0)
