### ISSUE TITLE
update

### ISSUE THREAD

**Issue by AroKol78** [JustOff/lull-the-tabs#15]
please do the updates `lull-the-tabs` (maybe more `cookies-exterminator`,`ca-archive`,...)
https://github.com/JustOff/lull-the-tabs/blob/266079ab421ab182baad467af47dd715ad52e86a/install.rdf#L18

**Comment by JustOff** [comment]
There is no need for this, and [here's why](https://developer.mozilla.org/en-US/docs/Archive/Add-ons/Install_Manifests#targetApplication):

> while `<em:maxVersion>` is a required property, it is ignored unless you also set `<em:strictCompatibility>`
