### ISSUE TITLE
Tab order slightly changes when recovering a session with browser start

### ISSUE THREAD

**Issue by Gordon-Dry** [JustOff/lull-the-tabs#16]
Using Pale Moon 29.1.1

Single tabs are moved one or more positions to the right when this addon is enabled.
This occurs after the browser was closed - with saving the session - and opened - with recovering the session.

**Comment by JustOff** [comment]
Please provide the steps to reproduce this issue using a new, unmodified browser profile where LTT is the only extension.

**Comment by JustOff** [comment]
The required information is not provided by the reporter.
