### ISSUE TITLE
Tab strip gets scrolled when tab is unloaded.

### ISSUE THREAD

**Issue by wolfbeast** [JustOff/lull-the-tabs#3]
It seems there's a brief focus shift on the tab that is getting unloaded which will cause the tab strip to attempt to scroll the tab into view; this results in sudden uninitiated shifting of tab positions in the UI.

**Comment by JustOff** [comment]
It's quite possible, but you need to have a really sharp eye to notice it) The fact is that I have two ways to replace the tab I unload with a new pending one: call `gBrowser.swapBrowsersAndCloseOther` or call `gBrowser.moveTabTo`, and then close the original. The first option conflicts with future calls of "Find in page", and the second leads to the effect you described. I can't yet come up with a solution that eliminates both shortcomings.

**Comment by wolfbeast** [comment]
Actually, depending on the side of the active tab the unloading tab is, and the distance it is away from it (whether it is in view or not) it can completely swap the tab strip's orientation (active tab being on the other edge of the browser suddenly). I think the solution would be to somehow prevent the call to scroll the tab into view.

**Comment by JustOff** [comment]
> it can completely swap the tab strip's orientation

Wow, then it certainly can be very annoying. Apparently I did not encounter this, because I use multi-row tabs and all tabs are always visible.

> somehow prevent the call to scroll the tab into view

Yes, I thought about something like this, or even better to temporarily suspend the UI update during unloading. Unfortunately, I still can't find which API is responsible for this.

**Comment by JustOff** [comment]
@wolfbeast, please try [1.3.4b1](https://github.com/JustOff/lull-the-tabs/releases/download/1.3.3/lull-the-tabs-1.3.4b1.xpi).

**Comment by wolfbeast** [comment]
Preliminary testing results are good, with no "ghost scrolling" being seen so far, although for some reason my tab animation got switched off when installing it and I had to reset it and then restart the browser for the extension to work properly.

**Comment by JustOff** [comment]
Please try [1.3.4b2](https://github.com/JustOff/lull-the-tabs/releases/download/1.3.3/lull-the-tabs-1.3.4b2.xpi), it should workaround this issue more carefully.

**Comment by JustOff** [comment]
@wolfbeast, I assume the problem with disabling of tab animation has been resolved in the latest beta, so I'm going to release 1.3.4 and close this issue. Let me know if something else needs to be addressed here.

**Comment by wolfbeast** [comment]
I've given it an extensive run and haven't seen any further issues, so yes, you can consider this resolved.

**Comment by JustOff** [comment]
Thanks for the confirmation.
