### ISSUE TITLE
[Bug] Break Tab Kit 2 Tabs Tree Style (Indentation)!

### ISSUE THREAD

**Issue by misakitchi** [JustOff/lull-the-tabs#4]
I use Tab Kit 2 for Tabs Tree Style
When tab is unloaded it break the indentation: no more Tabs Tree Style... :(

Before:
![palemoon27 - lull the tabs - before](https://user-images.githubusercontent.com/9465756/38455116-9b6bddc6-3a62-11e8-8ddb-3d5051c8ea84.jpg)

After:
![palemoon27 - lull the tabs - after](https://user-images.githubusercontent.com/9465756/38455117-a53dada2-3a62-11e8-947c-ff79def2d54f.jpg)

Can you do something please? :)

**Comment by JustOff** [comment]
As far as I see from the Tab Kit 2 sources it does not provide API necessary to move tabs in the subtree to another parent, so LTT can't preserve trees when unloading like it [does so for Tree Style Tab](https://github.com/JustOff/lull-the-tabs/blob/7b1292ef47245ea5b7bf188e1a2e65e97a3a701c/bootstrap.js#L546).

I can hardly do anything about this without @PikachuEXE's [help](https://github.com/tabkit/tabkit2/issues/144).

**Comment by misakitchi** [comment]
Hello! Some news on this issue?

**Comment by JustOff** [comment]
Unfortunately, as you can see, I have not received any response from the author of Tab Kit 2.

**Comment by PikachuEXE** [comment]
Let me take a look next week
I don't get long enough holiday often

I guess I missed the last notification

**Comment by misakitchi** [comment]
I don't understand what you have done, because i see no change... but thanks! :)

**Comment by misakitchi** [comment]
Thanks for the new version! :)

**Comment by PikachuEXE** [comment]
Guess I can throw away BarTab and install this instead :)
