### ISSUE TITLE
Use default browser behavior when opening new tab in background - Improvment/bug?

### ISSUE THREAD

**Issue by Ower8x** [JustOff/lull-the-tabs#7]
Hi not sure if this is a bug or not, or I am missing something in the options:
currently when I have the extension enabled and prevent background tabs from loading the new background tabs are open either at the end of all Tabs or can be set to open right next to the active tab.
My inquiry is is it possible to have the standard behavior when the new tab opens at the end of the current tab group, either in the current version or added in a future one?
thanks in advance
Ower8x

**Comment by JustOff** [comment]
It seems there really was a bug, please try [LTT 1.4.3b1](https://github.com/JustOff/lull-the-tabs/releases/download/1.4.2/lull-the-tabs-1.4.3b1.xpi).
